---
title: "Heritability"
author: "Oluwafemi Oyedele"
date: "2023-02-07"
output: html_document
---

```{r setup, include=FALSE}
library(agridat)
library(emmeans)
library(lme4)
library(tidyverse)
library(readxl)
library(here)
knitr::opts_chunk$set(echo = TRUE)
```


```{r,'02',cache=TRUE,dependson='dat1'}
# Import the data set into R -----------------------------------------------
dat1 <- read_excel(path = here::here('data/Tunde G2 datasets.xlsx'))
```

# Convert all the Characters to factor ------------------------------------
```{r,'03',cache=TRUE,dependson='dat1'}
dat1 <- dat1 %>%
  mutate(across(.cols = c(1:4),.fns = factor))
```
# Drop all the missing data -----------------------------------------------
```{r,'04',cache=TRUE,dependson='dat1'}
dat1 <- dat1 %>%
  drop_na()
```

## Tuber Weight

# fit model ---------------------------------------------------------------
# random genotype effect

```{r,'05',cache=TRUE,dependson='dat1'}
g_ran <- lmer(data    = dat1,
              formula = `tuber weight` ~ rep_number + (1|accession_name) + (1|rep_number:block_number))

```

# fixed genotype effect

```{r,'06',cache=TRUE,dependson='dat1'}
g_fix <- lmer(data    = dat1,
              formula = `tuber weight` ~ rep_number +    accession_name  + (1|rep_number:block_number))
```

# handle model estimates --------------------------------------------------
# genotypic variance component

```{r,'07',cache=TRUE,dependson='dat1'}
vc.g <- g_ran %>%
  VarCorr %>%
  as_tibble %>%
  filter(grp=="accession_name") %>%
  pull(vcov) # 0.1429021

vc.g
```
# mean variance of a difference between genotypes

```{r,'08',cache=TRUE,dependson='dat1'}
vdBLUE.avg <- g_fix %>%
  emmeans(pairwise ~ accession_name) %>%
  pluck("contrasts") %>%
  as_tibble %>%
  mutate(Var=SE^2) %>%
  pull(Var) %>%
  mean #

vdBLUE.avg
```

# H2 Piepho ---------------------------------------------------------------
```{r,'09',cache=TRUE,dependson='dat1'}
H2.p <- vc.g/(vc.g + vdBLUE.avg/2)
H2.p
```

