on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

name: 07-saving-results

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
       runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install GDebi first
      run: sudo apt-get install gdebi-core
    - name: Download the deb file
      run: sudo curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
    - name: Install the deb file
      run: sudo apt-get install -y ./quarto-linux-amd64.deb
    - name: Verify Install
      run: /usr/local/bin/quarto check
    - name: render site
      run: quarto render
    - name: "script/UfoumaAnova_01.qmd"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages:
            any::tidyverse
            any::readxl
            any::emmeans
            any::lme4
            any::rmarkdown
            any::lmerTest
            any::here
            any::skimr
            any::VIM
            any::mice
            any::knitr

      - name: script
        #run: Rscript -e 'quarto render("script/UfoumaAnova_01.qmd")'


      - name: commit files
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m "Saving the results" || echo "no changes to commit"
          git push origin || echo "no changes to commit"
